/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a agent by ID */
        get: operations["getAgent"];
        /** Update a agent */
        put: operations["updateAgent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query agents (non-destructive read) */
        post: operations["queryAgents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get agent counts by status */
        post: operations["agentStats"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read a agent (non-destructive, optional blocking) */
        post: operations["readAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/take": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Take a agent (destructive read) */
        post: operations["takeAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Blocking take operation */
        post: operations["inAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a agent as completed */
        post: operations["completeAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/complete-and-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a agent and create output agents atomically */
        post: operations["completeAndOutAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release ownership of a agent */
        post: operations["releaseAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew lease for a agent */
        post: operations["renewLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get events */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query telemetry spans
         * @description Results are namespace-scoped to the authenticated principal when auth is enabled.
         */
        get: operations["listTelemetrySpans"];
        put?: never;
        /**
         * Ingest telemetry spans
         * @description Namespace scope is derived from the authenticated principal when auth is enabled.
         */
        post: operations["ingestTelemetrySpan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry/spans:batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest telemetry spans (batch)
         * @description Namespace scope is derived from the authenticated principal when auth is enabled.
         */
        post: operations["ingestTelemetrySpanBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/shards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect the static shard map
         * @description Admin-only. Writer connection details are redacted to host, port, database, and sslmode.
         */
        get: operations["getShardMap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/shards/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect shard health
         * @description Admin-only operational endpoint.
         */
        get: operations["getShardHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/shards/queues/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inspect queue stats for the owning shard
         * @description Admin-only operational endpoint.
         */
        get: operations["getShardQueueStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dag/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get DAG for a agent */
        get: operations["getDAG"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system statistics
         * @description Admin-only operational endpoint.
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Agent: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            id: string;
            /** @description Type/category of the agent */
            kind: string;
            /**
             * @description Current status
             * @enum {string}
             */
            status: "NEW" | "IN_PROGRESS" | "COMPLETED" | "FAILED" | "CANCELLED";
            /** @description Actual data payload */
            payload?: {
                [key: string]: unknown;
            };
            /** @description Tags for filtering */
            tags?: string[];
            /** @description Agent that owns this agent */
            owner?: string;
            /**
             * Format: uuid
             * @description Parent agent ID for DAG relationships
             */
            parent_id?: string;
            /**
             * Format: uuid
             * @description Distributed tracing ID
             */
            trace_id?: string;
            /** @description Namespace isolation identifier enforced by server auth principal */
            namespace_id?: string;
            /** @description Physical shard identifier for the owning backend partition */
            shard_id?: string;
            /** @description Time to live in seconds */
            ttl?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description When ownership was taken
             */
            owner_time?: string;
            /** @description Lease token for the current claim */
            lease_token?: string;
            /**
             * Format: date-time
             * @description Lease expiry timestamp
             */
            lease_until?: string;
            /** @description Monotonic agent version */
            version?: number;
            /** @description Additional metadata */
            metadata?: {
                [key: string]: string;
            };
        };
        CreateAgentRequest: {
            /** @description Type/category of the agent */
            kind: string;
            /** @description Actual data payload */
            payload: {
                [key: string]: unknown;
            };
            /** @description Tags for filtering */
            tags?: string[];
            /**
             * Format: uuid
             * @description Parent agent ID for DAG relationships
             */
            parent_id?: string;
            /**
             * Format: uuid
             * @description Distributed tracing ID (auto-generated if not provided)
             */
            trace_id?: string;
            /** @description Namespace identifier (ignored unless server permits override) */
            namespace_id?: string;
            /** @description Time to live in seconds */
            ttl?: number;
            /** @description Additional metadata */
            metadata?: {
                [key: string]: string;
            };
            obs?: components["schemas"]["TelemetryObs"];
        };
        UpdateAgentRequest: {
            /** @description Updated payload data */
            payload?: {
                [key: string]: unknown;
            };
            tags?: string[];
            metadata?: {
                [key: string]: string;
            };
            obs?: components["schemas"]["TelemetryObs"];
        };
        Query: {
            /** @description Filter by agent kind */
            kind?: string;
            /**
             * @description Filter by status
             * @enum {string}
             */
            status?: "NEW" | "IN_PROGRESS" | "COMPLETED" | "FAILED" | "CANCELLED";
            /** @description Filter by tags (AND condition) */
            tags?: string[];
            /** @description Filter by owner */
            owner?: string;
            /**
             * Format: uuid
             * @description Filter by parent ID
             */
            parent_id?: string;
            /**
             * Format: uuid
             * @description Filter by trace ID
             */
            trace_id?: string;
            /** @description Namespace filter (server-enforced from auth principal when authenticated) */
            namespace_id?: string;
            /** @description Agent ID used for ownership on take/in */
            agent_id?: string;
            /** @description Filter by metadata (exact match) */
            metadata?: {
                [key: string]: string;
            };
            /** @default 100 */
            limit: number;
            /** @default 0 */
            offset: number;
        };
        TakeRequest: {
            query?: components["schemas"]["Query"];
            obs?: components["schemas"]["TelemetryObs"];
        };
        InRequest: {
            query: components["schemas"]["Query"];
            /**
             * @description Timeout in seconds
             * @default 30
             */
            timeout: number;
            obs?: components["schemas"]["TelemetryObs"];
        };
        ReadRequest: {
            query: components["schemas"]["Query"];
            /**
             * @description Timeout in seconds (blocking read only)
             * @default 30
             */
            timeout: number;
            /**
             * @description Whether to block until a agent is available
             * @default false
             */
            blocking: boolean;
        };
        CompleteAgentRequest: {
            /** @description Completion result data */
            result: {
                [key: string]: unknown;
            };
            /** @description Optional shard routing hint returned from the original claim */
            shard_id?: string;
            obs?: components["schemas"]["TelemetryObs"];
        };
        CompleteAndOutRequest: {
            /** @description Completion result data */
            result: {
                [key: string]: unknown;
            };
            /** @description Optional shard routing hint returned from the original claim */
            shard_id?: string;
            outputs: components["schemas"]["CreateAgentRequest"][];
            obs?: components["schemas"]["TelemetryObs"];
        };
        CompleteAndOutResponse: {
            completed: components["schemas"]["Agent"];
            created: components["schemas"]["Agent"][];
        };
        ReleaseRequest: {
            /**
             * @description Optional reason for release (e.g., "lease_expired" for reaper releases)
             * @example lease_expired
             */
            reason?: string;
            /** @description Optional shard routing hint returned from the original claim */
            shard_id?: string;
            obs?: components["schemas"]["TelemetryObs"];
        };
        RenewLeaseRequest: {
            /** @description Optional lease duration override in seconds */
            lease_sec?: number;
            /** @description Optional shard routing hint returned from the original claim */
            shard_id?: string;
        };
        AgentStatsResponse: {
            counts?: {
                [key: string]: number;
            };
            total?: number;
        };
        Event: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tuple_id: string;
            /** @enum {string} */
            type: "CREATED" | "CLAIMED" | "UPDATED" | "COMPLETED" | "FAILED" | "RELEASED";
            /** Format: date-time */
            timestamp: string;
            agent_id?: string;
            data?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            trace_id?: string;
            version?: number;
        };
        DAG: {
            nodes: {
                [key: string]: components["schemas"]["DAGNode"];
            };
            edges: components["schemas"]["Edge"][];
        };
        DAGNode: {
            /** Format: uuid */
            tuple_id: string;
            kind: string;
            /** @enum {string} */
            status: "NEW" | "IN_PROGRESS" | "COMPLETED" | "FAILED" | "CANCELLED";
            /** Format: date-time */
            created_at: string;
            metadata?: {
                [key: string]: string;
            };
        };
        Edge: {
            /** Format: uuid */
            from: string;
            /** Format: uuid */
            to: string;
            /** @enum {string} */
            type: "parent" | "spawned" | "depends_on";
        };
        TelemetryObs: {
            trace?: components["schemas"]["TelemetryTrace"];
            /** @description Experiment assignments or treatment labels */
            treatments?: {
                [key: string]: unknown;
            };
            metrics?: components["schemas"]["TelemetryMetric"][];
            guardrails?: components["schemas"]["TelemetryGuardrail"][];
            events?: components["schemas"]["TelemetryEvent"][];
        };
        TelemetryTrace: {
            /** Format: uuid */
            trace_id?: string;
            /** Format: uuid */
            span_id?: string;
            /** Format: uuid */
            parent_span_id?: string | null;
            /** @description Optional call identifier for pairing */
            call_id?: string;
            links?: components["schemas"]["TelemetryLink"][];
        };
        TelemetryLink: {
            /** Format: uuid */
            span_id?: string;
            /** @description Link type (e.g., depends_on) */
            type?: string;
        };
        TelemetryMetric: {
            key: string;
            value_bool?: boolean | null;
            value_num?: number | null;
            value_str?: string | null;
        };
        TelemetryGuardrail: {
            rule_id: string;
            hit: boolean;
            severity?: string;
            evidence_ref?: string;
        };
        TelemetryEvent: {
            name: string;
            kind?: string;
            /** Format: date-time */
            ts_start: string;
            /** Format: date-time */
            ts_end?: string | null;
            status?: string;
            attrs?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            span_id?: string;
            /** Format: uuid */
            parent_span_id?: string | null;
        };
        TelemetrySpan: {
            /** Format: uuid */
            trace_id: string;
            /** Format: uuid */
            span_id?: string;
            /** Format: uuid */
            parent_span_id?: string | null;
            /** Format: uuid */
            tuple_id?: string;
            name: string;
            kind?: string;
            /** Format: date-time */
            ts_start: string;
            /** Format: date-time */
            ts_end?: string | null;
            status?: string;
            attrs?: {
                [key: string]: unknown;
            };
            metric?: components["schemas"]["TelemetryMetric"];
            call_id?: string;
            links?: components["schemas"]["TelemetryLink"][];
        };
        TelemetrySpanBatch: {
            spans: components["schemas"]["TelemetrySpan"][];
        };
        Error: {
            /** @description Error code */
            error: string;
            /** @description Human-readable error message */
            message: string;
            /** @description Additional error details */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            /** @description Agent created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description Agent updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    queryAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Query"];
            };
        };
        responses: {
            /** @description Query results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        agents?: components["schemas"]["Agent"][];
                        /** @description Total number of matching agents */
                        total?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    agentStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Query"];
            };
        };
        responses: {
            /** @description Agent counts by status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentStatsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    readAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadRequest"];
            };
        };
        responses: {
            /** @description Agent read successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description No matching agent found */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description Request timeout (blocking read) */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    takeAgent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Agent ID used for ownership on take */
                "X-Agent-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakeRequest"];
            };
        };
        responses: {
            /** @description Agent taken successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description No matching agent found */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    inAgent: {
        parameters: {
            query?: never;
            header?: {
                /** @description Agent ID used for ownership on take */
                "X-Agent-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InRequest"];
            };
        };
        responses: {
            /** @description Agent taken successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Request timeout */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    completeAgent: {
        parameters: {
            query?: never;
            header: {
                /** @description Agent ID completing the agent */
                "X-Agent-ID": string;
                /** @description Lease token for the agent claim */
                "X-Lease-Token": string;
                /** @description Optional response preference. Use `return=minimal` to receive 204 with no agent body. */
                Prefer?: string;
            };
            path: {
                /** @description Agent ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteAgentRequest"];
            };
        };
        responses: {
            /** @description Agent completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Agent completed successfully with minimal response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    completeAndOutAgent: {
        parameters: {
            query?: never;
            header: {
                /** @description Agent ID completing the agent */
                "X-Agent-ID": string;
                /** @description Lease token for the agent claim */
                "X-Lease-Token": string;
            };
            path: {
                /** @description Agent ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteAndOutRequest"];
            };
        };
        responses: {
            /** @description Agent completed and outputs created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteAndOutResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    releaseAgent: {
        parameters: {
            query?: never;
            header: {
                /** @description Agent ID releasing the agent */
                "X-Agent-ID": string;
                /** @description Lease token for the agent claim */
                "X-Lease-Token": string;
            };
            path: {
                /** @description Agent ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            /** @description Agent released successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Forbidden - cannot release agent not owned by this agent */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    renewLease: {
        parameters: {
            query?: never;
            header: {
                /** @description Agent ID renewing the lease */
                "X-Agent-ID": string;
                /** @description Lease token for the agent claim */
                "X-Lease-Token": string;
            };
            path: {
                /** @description Agent ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RenewLeaseRequest"];
            };
        };
        responses: {
            /** @description Lease renewed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Forbidden - cannot renew lease not owned by this agent */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Agent not in correct state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /** @description Filter by agent ID */
                tuple_id?: string;
                /** @description Filter by agent ID */
                agent_id?: string;
                /** @description Filter by event type */
                type?: "CREATED" | "CLAIMED" | "UPDATED" | "COMPLETED" | "FAILED" | "RELEASED";
                /** @description Filter by trace ID (for causal debugging) */
                trace_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events?: components["schemas"]["Event"][];
                        total?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listTelemetrySpans: {
        parameters: {
            query: {
                /** @description Filter by trace ID */
                trace_id: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telemetry span list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        spans?: components["schemas"]["TelemetrySpan"][];
                        total?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    ingestTelemetrySpan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetrySpan"];
            };
        };
        responses: {
            /** @description Telemetry span ingested */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Number of spans ingested */
                        ingested?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    ingestTelemetrySpanBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetrySpanBatch"];
            };
        };
        responses: {
            /** @description Telemetry spans ingested */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Number of spans ingested */
                        ingested?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getShardMap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shard map information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not supported by the current backend */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getShardHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-shard health information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not supported by the current backend */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getShardQueueStats: {
        parameters: {
            query: {
                namespace_id: string;
                queue: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue statistics for the routed shard */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not supported by the current backend */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDAG: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Root agent ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DAG structure */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DAG"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "healthy" | "degraded" | "unhealthy";
                        /** @enum {string} */
                        backend?: "postgres" | "sqlite" | "unknown";
                        version?: string;
                    };
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Total number of agents */
                        agents?: number;
                        /** @description Total number of events */
                        events?: number;
                        /** @description Number of active agents */
                        active_agents?: number;
                        /** @enum {string} */
                        backend?: "postgres" | "sqlite" | "unknown";
                    };
                };
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
